### ISSUE TITLE
Why *= in place of * ?

### ISSUE THREAD

**Issue by shaneasd** [pulver/autodiff#12]
I notice that in the implementation of asin when sqrt(1-d1\*d1) is evaluated, instead d1\*=d1 is used. I can't figure out why \*= would be used here since the resulting expression is eventually assigned to d1 anyway. Initially I figured this was some esoteric property of the relevant operators causing this to generate faster assembly but I also notice in the fourth_power.cpp example you do the same thing. As a user I would assume I would need to emulate that same pattern but not know why.

Is there a reason for these pieces of code to be written this way? If not, I think it would be better to use operator\* instead. If so, it would be good for the documentation to explain why.

**Comment by pulver** [comment]
> As a user I would assume I would need to emulate that same pattern but not know why.

It's not needed. It's an (attempted) optimization to prevent an extra instance from being made. That is, `a*b` returns a third `autodiff_fvar` instance. In contrast, `a*=b` modifies `a` which is just as fast as the former, but does not return a third instance; it returns a reference to the modified `a`.

For example, in `apply_with_horner()`, there is the loop:

    for (size_t i=order_sum ; i-- ;)
        (accumulator *= epsilon) += f(i) / boost::math::factorial<root_type>(i);

It is instances such as this where using the arithmetic-assignment operators pay off, especially for large array dimensions.

Hope I have understood your question. It's possible that the compiler will intelligently make these optimizations anyway, and writing it in this way doesn't actually help, but that is the intent.

**Comment by shaneasd** [comment]
Thanks for the response. You certainly do appear to have understood the question.

I think the apply_with_horner case is not analogous since the use of *= (and += for that matter) is required. It is important that it modify the accumulator. If the code instead read
```
for (size_t i=order_sum ; i-- ;)
    (accumulator *= epsilon) += f(i) / boost::math::factorial<root_type>(i);
```
then as far as I can see the whole loop would be pointless.

This is an optimization I haven't encountered before. I suspect in the case of fourth_power the operator* would not create a temporary due to [named return value optimization](https://en.cppreference.com/w/cpp/language/copy_elision) but admittedly this would depend on the optimizer.

I'm not certain about this but it seems to me that in
```
template<typename T>
T fourth_power(T x)
{
    x *= x;
    return x *= x;
}
```
the fact that x*=x is a T& will force a copy constructor to run, defeating copy elision. By comparison, if x*x were used then x*x is a prvalue so the copy in the return of fourth_power would be elided. Supposing that I'm right then it would appear that you have optimized away a potential (Dependent on optimizer) unnecessary copy but, in doing so, caused a guaranteed copy.

In the asin case I as curious to see how the d1*=d1 would be used in the broader expression. It looks like when it is subtracted from 1 the code is
```
fvar<RealType,Order> operator-(const typename fvar<RealType,Order>::root_type& ca, const fvar<RealType,Order>& cr)
{
    return -cr += ca;
}
```
If the optimization we're discussing is indeed worthwhile then should a similar optimization be applied to the expression ```-cr``` e.g. something like
```
{
    cr.negate();
    return cr += ca;
}
```

**Comment by pulver** [comment]
> the fact that x\*=x is a T& will force a copy constructor to run, defeating copy elision. By comparison, if x\*x were used then x\*x is a prvalue so the copy in the return of fourth_power would be elided. Supposing that I'm right then it would appear that you have optimized away a potential (Dependent on optimizer) unnecessary copy but, in doing so, caused a guaranteed copy.

I agree with your reasoning, and will make these changes. It is also distracting to the `fourth_power.cpp` example, which may suggest to some that this is necessary, as you earlier pointed out. Thanks for bringing this up.

**Comment by pulver** [comment]
> the fact that x\*=x is a T& will force a copy constructor to run, defeating copy elision. By comparison, if x\*x were used then x\*x is a prvalue so the copy in the return of fourth_power would be elided. Supposing that I'm right then it would appear that you have optimized away a potential (Dependent on optimizer) unnecessary copy but, in doing so, caused a guaranteed copy.

I follow what you are saying, but since the underlying data structure for `fvar` is a `std::array<>`, (rather than a `std::vector<>` for instance) I wonder if a copy is always inevitable in such cases. That is, when the following is called,

    autodiff_fvar<double,Order> y = fourth_power(x);

`y` is allocated on the stack prior to the function call (unlike a `std::vector<>`). Thus whether the return statement within `fourth_power()` is `return x*=x;` or `return x*x;` both will always get copied to `y`. The only scenario I can see when the compiler optimizer could avoid this is to use the memory space for `y` for the variable `x` itself within `fourth_power()` from the very beginning (in which case the `return x*=x;` would be a better hint to the compiler for such an optimization. I don't claim that this optimization is likely to occur.)

I still agree however that `return x*x;` is less confusing.

**Comment by shaneasd** [comment]
I think what that article is saying is explicitly that ```x*x``` will not get copied to ```y```. ```y```s memory will be directly used to receive the value of ```x*x``` rather than space for x*x being allocated on the stack and then copied into y at the return.

I did an experiment in MSVC++15.9.4.
```
#include <iostream>
#include <array>

struct X
{
	X(float a, float b)
	{
		m_data.at(0) = a;
		m_data.at(0) = b;
	}
	X(const X& x)
	{
		std::cout << "Copying\n";
	}
	std::array<float, 2> m_data;
	X& operator*=(const X& other)
	{
		return *this;
	}
	X operator*(const X& other)
	{
		return X(1, 2);
	}
};

template<typename T>
T fourth_power(T x)
{
	x *= x;
	return x * x;
}

int main()
{
	volatile float a = 1, b = 2;
	X x = fourth_power(X(a, b));
	a = x.m_data.at(0);
	b = x.m_data.at(1);
}
```

In this example no copies are performed (based off console output) in either debug (i,e, without optimizations) and release (with /O2). for the ```x*=x``` variant one copy is performed in both debug and release. Note that copy elision in this case is not an optional optimization, it is a requirement of the standard. I tried removing the side effect from the copy constructor and using /O2 instead inspecting the assembly and it looks like in my simple case the entire call to fourth_power gets optimized away in either case.

**Comment by shaneasd** [comment]
I can create a PR for this if you'd like

**Comment by pulver** [comment]
That is very interesting! Copy elision runs deeper than I had expected. Here is a test that prints out the memory addresses of variables in the fourth_power example:

```c++
#include <boost/math/differentiation/autodiff.hpp>
#include <iostream>

template<typename T>
T fourth_power(T x)
{
    x *= x;
    return x * x;
}

int main()
{
    using namespace boost::math::differentiation;
    constexpr int Order=5; // The highest order derivative to be calculated.

    autodiff_fvar<double,Order> x = make_fvar<double,Order>(2.0); // Find derivatives at x=2.
    autodiff_fvar<double,Order> y = fourth_power(x);
    autodiff_fvar<double,Order> z;
    std::cout << "     &x = " << &x << std::endl;
    std::cout << "     &y = " << &y << std::endl;
    std::cout << "     &z = " << &z << std::endl;
    for (int i=0 ; i<=Order ; ++i)
        std::cout << "y.derivative("<<i<<") = " << y.derivative(i) << std::endl;
    return 0;
}
```
In autodiff.hpp, `operator*()` is modifed as:
```c++
template<typename RealType, size_t Order>
template<typename RealType2, size_t Order2>
promote<fvar<RealType,Order>,fvar<RealType2,Order2>>
    fvar<RealType,Order>::operator*(const fvar<RealType2,Order2>& cr) const
{
    const promote<RealType,RealType2> zero(0);
    promote<fvar<RealType,Order>,fvar<RealType2,Order2>> a;
    promote<fvar<RealType,Order>,fvar<RealType2,Order2>> retval;
    promote<fvar<RealType,Order>,fvar<RealType2,Order2>> b;
    std::cout << "     &a = " << &a << std::endl;
    std::cout << "&retval = " << &retval << std::endl;
    std::cout << "     &b = " << &b << std::endl;
    if BOOST_AUTODIFF_IF_CONSTEXPR (Order < Order2)
        for (size_t i=0, j=Order, k=Order2 ; i<=Order2 ; ++i, j&&--j, --k)
            retval.v[i] = std::inner_product(v.cbegin(), v.cend()-j, cr.v.crbegin()+k, zero);
    else
        for (size_t i=0, j=Order2, k=Order ; i<=Order ; ++i, j&&--j, --k)
            retval.v[i] = std::inner_product(cr.v.cbegin(), cr.v.cend()-j, v.crbegin()+k, zero);
    return retval;
}
```
Output:
```
     &a = 0x7fff7bb2fdb0
&retval = 0x7fff7bb2fed0 // Same as &y!
     &b = 0x7fff7bb2fd80
     &x = 0x7fff7bb2ff00
     &y = 0x7fff7bb2fed0
     &z = 0x7fff7bb2fea0
```
In `main()`, 3 local fixed-size variables are declared in succession: `x`, `y`, and `z`, and as expected their memory addresses are sequential.
In `operator*()`, 3 local fixed-size variables are declared in succession: `a`, `retval`, `b`. However since `retval` gets returned and is used to initialize `y`, the compiler was smart enough to use the memory space of `y` for `retval`.
Thank you for spelling this out and bringing it to my attention. I'll make some updates with this in mind.

**Comment by shaneasd** [comment]
Cool. Keep in mind, I think the copy elision done in retval is actually the kind that is not required but is permitted by the standard. Practically I don't know what compilers do it in this case but it's probably reasonable to leave this optimization to the compiler one way or the other.

**Comment by pulver** [comment]
Right. This is precisely the [named return value optimization](https://en.cppreference.com/w/cpp/language/copy_elision) you referred to earlier:

> Under the following circumstances, the compilers are permitted, but not required to omit the copy [and move (since C++11)] construction of class objects even if the copy[/move (since C++11)] constructor and the destructor have observable side-effects. The objects are constructed directly into the storage where they would otherwise be copied/moved to.
>
> * In a return statement, when the operand is the name of a non-volatile object with automatic storage duration, which isn't a function parameter or a catch clause parameter, and which is of the same class type (ignoring cv-qualification) as the function return type. This variant of copy elision is known as NRVO, "named return value optimization".

**Comment by pulver** [comment]
For `operator-(ca,cr)`, previous version was `return -cr += ca;` which was not making use of copy elision. New version is:
```c++
fvar<RealType,Order> mcr = -cr; // has same address as retval in operator-() due to NRVO
mcr += ca;
return mcr; // <-- This uses NRVO. The following does not. --> return mcr += ca;
```
Thus when calling `auto y = 7.0 - x;`, the variables `y`, `mcr`, and `retval` in:
```c++
template<typename RealType, size_t Order>
fvar<RealType,Order> fvar<RealType,Order>::operator-() const
{
    fvar<RealType,Order> retval;
    for (size_t i=0 ; i<=Order ; ++i)
        retval.v[i] = -v[i];
    return retval;
}
```
all have the same memory address (with gcc 7.3.1). 3 local variables in 3 different scopes are all actually the same.
NRVO is a nice optimization!

Unless you see any other places I'm missing (on develop branch), I'll close this issue.

**Comment by shaneasd** [comment]
I notice you didn't change the asin case which I mentioned earlier. Not sure if you concluded this was different in some way?
In any case, my primary concern was the clarity of the fourth_power example and that is addressed.

**Comment by pulver** [comment]
> I notice you didn't change the asin case which I mentioned earlier. Not sure if you concluded this was different in some way?

It seems like it could possibly be more efficient than a non-assigment operator, but I haven't proven this, and welcome any evidence that there is a more efficient way to do it, perhaps by saving an extra copy or two. In the meantime I'm comfortable leaving it as is. As you said, since the `fourth_power` example has been updated, that should suggest that such operator-assignment techniques are not necessary.

**Comment by pulver** [comment]
Just made another [change](https://github.com/pulver/autodiff/commit/f7bb18dcccae985c36c217a3b154ab332b77bcec#diff-97728ef771217228bc509427fc36533b) to `fourth_power.cpp` on a separate dev branch:
```c++
template<typename T>
T fourth_power(const T& x)
{
    T x4 = x * x; // retval in operator*() uses x4's memory via named return value optimization (NRVO).
    x4 *= x4;     // No copies of x4 are made within operator*=() even when squaring.
    return x4;    // x4 uses y's memory in main() via NRVO (thus so does retval in operator*() above).
}
```
The improvement here is that no temporary instances are created, if the return value is used to initialize a new variable (`y` in `main()`) and the compiler supports NRVO (e.g. gcc since 3.1). This kind of optimization seems worthy of being included and commented on in the example. I hope it is not too confusing for new users of autodiff.

Feedback is welcome.

**Comment by shaneasd** [comment]
I can't see a way of achieving the same level of optimization with more clarity. The question is whether the optimization or the clarity is more important here. For my money I'd go with the clarity. The comments are certainly clear (at least to me, being familiar with the background discussion).

On a related note could you not provide a more optimal integer power implementation for fvar? I haven't given it a lot of thought but I'd imagine there'd be some optimizations you could make for powers more than 2.

**Comment by pulver** [comment]
Thanks for the feedback.

> On a related note could you not provide a more optimal integer power implementation for fvar?

No (if you delete "not' from your question, then yes). I also need to rewrite the other 2 overloads to not use `exp()` and `log()`. Perhaps I'll make that update at that time. (I assume you mean calculate `pow(x0,y)` once, and then divide the result by `x0` in each subsequent iteration without having to call `pow()` again.)

**Comment by shaneasd** [comment]
I totally agree with your second paragraph about optimizing integer powers. That's not exactly what I meant.

My question was more, assuming you had an appropriately optimal implementation of pow that could take full advantage of the knowledge that you're going to be taking derivatives (knowledge which fourth_power does not have) then would this method be more efficient than fourth_power at calculating an fvar representing x*x*x*x and if so is it misleading to use fourth_power as an example if that's not the best way of calculating a fourth power. I've thought about it some more since and I think the sort of thing I had in mind overlooked the complexity of later derivatives so my guess would be that an optimal implementation of pow is probably not as good as fourth_power but I'm not certain.

Your suggested optimization of pow(fvar, real) does look good though. In fact it looks like you could simplify that loop down to
```
    derivatives[0]= pow(x0, y);
    auto x0inv = 1/x0;
    for (i=1; i<=order && y != i ; ++i)
    {
        derivatives[i] = (y - i + 1)*derivatives[i-1]*x0inv;
    }
```

I do worry about precision issues in that ```y!=i``` (or equivalently ```coef!=0```) check though.

Reformulating the the pow(x, fvar) methods to not depend on exp/log sounds beyond my mathematical abilities. I'm very interested to see what that ends up looking like.

**Comment by kedarbhat** [comment]
Regarding equality/inequality/comparison precision, I added a function (fpequal) as a floating point equality/inequality predicate which just checks if lhs is both less than or equal to and greater than or equal to rhs. This is suboptimal, but I wrote it to satisfy clang  until the notion of actual equality is defined for these types.

Boost.Math provides some facilities for checking equality (relative and absolute, depending on how small in magnitude one or both operands is/are), but I hit a lot of corner cases, so decided to add this to my TODO list in favor of fixing some more obvious and pressing issues since fpequal is just an obsfucated operator== overload (when one really gets down to the heart of it).

**Comment by shaneasd** [comment]
I believe the issue I raised is appropriately resolved so I'm closing this issue. There's a lot more off-topic interesting discussion here but I don't think any of it constitutes a concrete issue.

If this is not the right etiquette please reopen.
