### ISSUE TITLE
cv qualifiers can break traits specializations

### ISSUE THREAD

**Issue by kedarbhat** [pulver/autodiff#15]
I noticed this as I was trying to clean up the MSVC issues. Basically, qualifiers will push us to the `root_type` specializations rather than the `fvar<typename, std::size_t>` specializations. Below is an example.
```
static_assert(get_depth<fvar<float, 4>>::value == 1);
static_assert(get_depth<const fvar<float, 4>>::value == 0);
```

I'm working through a solution, but I think we need to move away specializing on `fvar<RealType, std::size_t>` and should check for other traits that signal we have an `fvar` rather than a `root_type`. I think using the `void_t` idiom is the best way to go, since we can then require several types/fields to be present before going to the specialization meant for `fvar` types; we can check for depth, order_sum, and anything else to lower the probability of a `root_type` having those member types/fields confusing the type resolution.

**Comment by pulver** [comment]
Will `std::decay` do the job?

**Comment by kedarbhat** [comment]
Yes. I used `static_assert` statements as above to verify the problem existed in each `get_depth`, `get_order_sum`, and `is_fvar`. The PR contains `static_assert` statements to verify the the respective solutions (which are all similar to each other).

The blueprint solution used in each case works as so: 
A type is passed to an alias template, through which the type passes (transformed by `std::decay`) to one of two structs.

The structs (now in `detail` namespaces) are similar to those that existed before: one is not specialized, used previously only for non-`fvar` types, while the other is specialized for `fvar` types.

If an `fvar` type makes it to the unspecialized struct (as would happen with a const-qualified `fvar` type), that type is checked for `fvar`-ness, and passed to the specialized struct if it is indeed actually an `fvar`. This secondary check is for cases as below; that is, a nested `fvar` is const-qualified, which would otherwise stop the `order_sum` calculation.
`get_order_sum<fvar<const fvar<double, 4>, 4>`

**Comment by pulver** [comment]
Would you say this has been resolved?

**Comment by kedarbhat** [comment]
Yea, this was resolved in the last PR. I’ll close this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
