### ISSUE TITLE
root_type vs RealType

### ISSUE THREAD

**Issue by shaneasd** [pulver/autodiff#18]
What is the meaning of these two concepts. Intuitively I think of them both as the underlying binary representation of the number. However I presume it is not this simple or they needn't both exist. My guess is that RealType is allowed to be an fvar and root_type will recurse down through nested fvars to find the underlying type.

The reason I ask is I was playing with fvar of ```std::complex<double>``` by defining
```
template <typename T>
struct get_root_type<std::complex<T>> { using type = T; };
```
the problem with this is it necessitates replacing a bunch of root_types with RealTypes which seems to work but I presume will have messy consequences I haven't run into yet.

I realize std::complex isn't intended to be supported at the moment as it doesn't satisfy the boost real concept.

**Comment by pulver** [comment]
> My guess is that RealType is allowed to be an fvar and root_type will recurse down through nested fvars to find the underlying type.

Yes that's precisely correct.

**Comment by pulver** [comment]
Feel free to re-open if there is a further comment/question.
