### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jeking3** [pulver/autodiff#2]
It would be useful here to adopt the https://github.com/boostorg/boost-ci continuous integration suite to improve deliverable quality.

**Comment by pulver** [comment]
I will look into that, thank you!

**Comment by kedarbhat** [comment]
I have most of this working. Cppcheck/CoverityScan have been trouble to get working, but I have those commented out for now so that other work can progress. 

For AppVeyor, I’m having very long compilation times in MinGW compared to MSVC (link times in particular). I should have this solved (and Cygwin, which is currently commented out in favor of solving MinGW first), should be solved later today as well.

**Comment by pulver** [comment]
Anyone know why the maximum number of [hits](https://docs.codecov.io/docs/viewing-source-code) on the `develop` branch is 2?
https://codecov.io/gh/pulver/autodiff/src/develop/include/boost/math/differentiation/autodiff.hpp

For example, [`operator*()`](https://codecov.io/gh/pulver/autodiff/src/develop/include/boost/math/differentiation/autodiff.hpp#L788) is called numerous times from many functions, yet the maximum hit count within the function is still 2.

**Comment by kedarbhat** [comment]
Navigating code on my phone is pretty horrid, but there are more than 2 call sites using `operator*()`, right? One hypothesis, which could quickly proven false if so, if the number of call sites exceeds 2. This assumes no inlining/optimizations.

Another oddity (among others) is in `inverse_apply()`: `*derivatives = 1 / x0;` has 0 hits, which makes me think some level of optimization is happening.

In any case, I can contact [codecov.io](http://www.codecov.io)’s support to try to understand what’s going on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pulver** [comment]
> Navigating code on my phone is pretty horrid, but there are more than 2 call sites using operator*(), right? One hypothesis, which could quickly proven false iif the number of call sites exceeds 2, is that “hits” are bucketed by call site. This assumes no inlining/optimizations.

`test/test_autodiff1.cpp`, `power8` contains:
```
  auto x = make_fvar<T, n>(ca);
...
  x = x * x * x * x * x * x * x * x;
```
I would expect this alone to cause `operator*()` to be called 7 times. Added to all of the other tests that call it, I would expect this function to have one of the highest hit counts. But nothing exceeds 2. I'm hoping someone can enlighten my basic misunderstanding.

**Comment by kedarbhat** [comment]
Regarding hit count, I'm hypothesizing the number you see (2) is a function of the number of times the code is built (for codecov purposes). I'm trying to see how codecov parses the lcov/gcov output to display "2", but looking at older versions of code, I see a maximum of 3 hits, and for any which are implemented for C++17 and C++11/C++14 separately, I see 1 and 2 within those functions (respectively). At the time, we were only building with 1 version of g++, but with all 3 versions.

If the above is true, then the drop from 3 to 2 is likely an artifact of something I'm doing incorrectly with b2/Jamfiles.

**Comment by pulver** [comment]
@jeking3 Any idea(s) how to fix this error `Can't locate PerlIO/gzip.pm` when running `lcov`?
https://travis-ci.com/pulver/autodiff/jobs/203155729
```
+lcov --gcov-tool=gcov-8 --base-directory /home/travis/build/pulver/boost-root/libs/autodiff --directory /home/travis/build/pulver/boost-root --capture --output-file all.info
Capturing coverage data from /home/travis/build/pulver/boost-root
Can't locate PerlIO/gzip.pm in @INC (you may need to install the PerlIO::gzip module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /tmp/lcov/bin/geninfo line 62.
BEGIN failed--compilation aborted at /tmp/lcov/bin/geninfo line 62.
```

**Comment by kedarbhat** [comment]
This file seems to pull in PerlIO::gzip:
https://github.com/ufal/treex/blob/master/.travis.yml

**Comment by jeking3** [comment]
I'm working on it.  lcov changed...

**Comment by jeking3** [comment]
All set; lcov had changed.  boost-ci updated; you can remove any lcov installation line in your .travis.yml as boost-ci does that now.

**Comment by pulver** [comment]
> All set; lcov had changed. boost-ci updated; you can remove any lcov installation line in your .travis.yml as boost-ci does that now.

Thanks, that fixed it.

Fyi I had to remove all 3 instances of `--rc lcov_branch_coverage=1` from `codecov.sh` otherwise the coverage percentage was much less (62%) than what it should be (100%). I don't understand why this was necessary, since this was applied to the `develop` branch: https://codecov.io/gh/pulver/autodiff/branch/develop

**Comment by jeking3** [comment]
It means you have 100% functional coverage, but 62% branch coverage.  This means 38% of your branches are untested.  I *only* measure coverage by branch coverage.

**Comment by pulver** [comment]
> It means you have 100% functional coverage, but 62% branch coverage. This means 38% of your branches are untested. I only measure coverage by branch coverage.

I was actually aiming for 100% **line coverage**:

```
+lcov --gcov-tool=gcov-8 --rc lcov_branch_coverage=1 --list coverage.info
Reading tracefile coverage.info
                                               |Lines      |Functions|Branches  
Filename                                       |Rate    Num|Rate  Num|Rate   Num
================================================================================
[/home/travis/build/pulver/boost-root/boost/math/]
...
differentiation/autodiff.hpp                   | 100%   531|90.2%  1k|58.2%  998
differentiation/autodiff_cpp11.hpp             | 100%   130|87.7% 721|57.0%  207
```
https://travis-ci.com/pulver/autodiff/jobs/203687424

Based on this [discussion](https://stackoverflow.com/questions/42003783/lcov-gcov-branch-coverage-with-c-producing-branches-all-over-the-place) it seems that to get full branch coverage also requires testing for complete exception handling. E.g. whenever `std::array<>::at()` is called, then we should also include a test to verify that an out-of-bounds exception is thrown at that point.

Is this the correct intent?

Would it "not count" or be inappropriate to report line coverage instead?

**Comment by jeking3** [comment]
Branch coverage means you have to force error conditions that are handled in your code.  For example if you catch ``std::out_of_bounds`` then you want a test to invoke that behavior and test that error handling code.  Otherwise branch coverage typically just means hitting every conditional in an if, switch, while, etc..

Since you are using boost-ci, you can look at the coverage in detail on codecov.io.  I have to admit, looking at some of the coverage on codecov.io leaves me a bit puzzled as to why some of the lines are yellow.  There's no real mouse-over description of "why" which is unfortunate.  I wonder if we're calling gcov and lcov properly.  I'll try to switch boost-ci to using the --coverage flag instead of the current -fprofile flags and see if it makes a difference.

**Comment by jeking3** [comment]
It made a small difference in coverage but not much, I've opened a codecov community question because I can't really understand why something like https://codecov.io/gh/boostorg/uuid/src/be5876a0fc9c2f7ad92eb95ba12e62d381e9068e/include/boost/uuid/random_generator.hpp#L130 is considered "yellow" when all lines surrounding it are "green".
