### ISSUE TITLE
Consider rearranging make_fvar template parameters

### ISSUE THREAD

**Issue by shaneasd** [pulver/autodiff#20]
Consider these two options
```
//This is copied straight from autodiff
template<typename RealType, size_t Order, size_t... Orders>
autodiff_fvar<RealType,Order,Orders...> make_fvar(const RealType& ca)
{
    return autodiff_fvar<RealType,Order,Orders...>(ca, true);
}

//This is the alternative I propose
template<size_t... Orders, typename RealType>
auto make_fvar2(const RealType& ca)
{
    return make_fvar<RealType, Orders...>(ca);
}
```
Calling these methods looks like
```
auto var = boost::math::differentiation::make_fvar<double, 1>(x);
auto var = boost::math::differentiation::make_fvar2<1>(x);
```

I like the latter case because the type is inferred. However there is a downside in that it *must* be inferred and cannot be specified (at least in my compiler. I haven't checked the standard). As such two equivalent calls in which you must be explicit about the type look like
```
auto var = boost::math::differentiation::make_fvar<double, 1>(x);
auto var = boost::math::differentiation::make_fvar2<1>(static_cast<double>(x));
```

Using this approach it would probably make sense to apply some rules for dealing with integers, i.e. ```make_fvar<1>(0)``` should probably do something sensible. Boost seems to address this by the rules documented here https://www.boost.org/doc/libs/1_62_0/libs/math/doc/html/math_toolkit/result_type.html .

Thoughts?

**Comment by pulver** [comment]
One motivation for the current case is the natural progression of types. That is, a type with 0 independent variables is of type `T` (e.g. `double`), a type for 1 independent variable has template parameters `<T,N1>` for example if one is interested in up to N1 derivatives, 2 independent variables has the second variable of type `<T,0,N2>`, etc. (Even though `make_fvar<T>(5.0)` doesn't compile, it might make sense at some point to add it.) This would be analogous to the progression in math of scalars, vectors, matrices, etc.

I've also been thinking about/planning to add a `make_fvar_tuple<T,N1,N2,N3,...>(10,11,12,...)` which would return a tuple of M independent variables initialized at the given values. This would save people from having to manually declare:
```
auto x = make_fvar<T,N1>(10);
auto y = make_fvar<T,0,N2>(11);
auto z = make_fvar<T,0,0,N3>(12);
...
```

In this case it would be preferred to put `T` first, rather than wrap each parameter in a `static_cast<T>()`. `autodiff_fvar<T,...>` also has `T` first, so in keeping things uniform/consistent this would add additional weight to keeping this convention for `make_fvar` too.

I'm reluctant to add a `make_fvar2` in the spirit of keeping the interface as minimal as possible. There is of course a benefit to convenience, as in the case of `make_fvar_tuple` which replaces multiple lines of code, but in the case of `make_fvar2` the convenience doesn't outweigh the increase in the API, IMO, at least based on what has been discussed so far.

**Comment by shaneasd** [comment]
I completely agree you don't want a second make_fvar function. My suggestion was that make_fvar might be the preferred version over make_fvar. As far as I can see you could similarly rearrange the template parameters of autodiff_fvar and related classes so I don't think that's an obstacle (though i haven't tried).

I'm not sure your argument about progression is valid. To my mind the progression from ```<>``` to ```<N1>``` to ```<0, N2>``` is no less sensible than ```<double>```, ```<double, N1>```, ```<double, 0, N2>```. If you were to permit ```make_fvar<double>(5.0)``` at some point it seems like the result object should be equivalent in behavior and layout to double such that a really good optimizer would make it a double and in fact you may even make that version of the method return a double. At that point ```make_fvar<double>(5.0)``` becomes equivalent to ```double(5.0)``` which seems redundant. Also interesting to note that if you allowed ```make_fvar<double>(5.0)``` then ```make_fvar(5.0)``` would work automatically.

I love the idea of make_fvar_tuple. I think counting zeros in template lists is quite inelegant, in stark contrast to the rest of the library. The tuple solution eliminates that issue. It would be great to be able to say ```auto [x, y, z] = make_fvar_tuple<double, 2, 4, 10>(1.0, 0.0, 0.0);```. However I think it would be even better to be able to say ```auto [x, y, z] = make_fvar_tuple<2, 4, 10>(1.0, 0.0, 0.0);```. In this case I can easily use ```0```, ```0.0f```, ```0.0``` to control my type. Unfortunately a more likely circumstance is that I have a handful of variables which I can't apply simple suffixes to, which leads to the situation ```auto [x, y, z] = make_fvar_tuple<2, 4, 10>(static_cast<double>(a), static_cast<double>(b), static_cast<double>(c));```. I agree this is pretty nasty.

I have a feeling there is a solution which avoids the static casts and allows template parameter deduction. Is it worth me giving it some more thought or do you prefer the specificity for other reasons?

How concerned are you by the fact that ```make_fvar_tuple<double, N1, N2, N3>``` mandates that all variables are of the same type? to me it seems likely that if you're working in floats you'll want floats all around but maybe there is a case where you'd want different precision for different variables?

**Comment by pulver** [comment]
> To my mind the progression from `<>` to `<N1>` to `<0, N2>` is no less sensible than `<double>`, `<double, N1>`, `<double, 0, N2>`.

Agreed. However the proposed definition of `make_fvar2` (I understand now it will be `make_fvar` in practice, but `make_fvar2` is used here to reference the proposed version) includes placing the type at the end. So it will actually be `<double>`, `<N1,double>`, `<0,N2,double>`, ... which is what I had in mind in contrasting this with the more "natural" progression of types of the current method. (At the same time I understand that the last type parameter can be excluded when it is inferred from the parameter.)

> As far as I can see you could similarly rearrange the template parameters of autodiff_fvar and related classes so I don't think that's an obstacle (though i haven't tried).

I don't think you can place a template parameter after a parameter pack, but if you can find a way to do it with `autodiff_fvar` then I would much more seriously consider the change you're proposing (no promises at this point though :)

**Comment by kedarbhat** [comment]
You can have template parameters after a parameter pack, but only in certain contexts. [Godbolt Compiler Explorer](https://godbolt.org/z/lbFNTS)

**Comment by shaneasd** [comment]
Oh no you're right, it's legit in make_fvar2 because the final parameter is inferred from the argument but that wouldn't be true for the class. From https://en.cppreference.com/w/cpp/language/parameter_pack

> In a primary class template, the template parameter pack must be the final parameter in the template parameter list. In a function template, the template parameter pack may appear earlier in the list provided that all following parameters can be deduced from the function arguments, or have default arguments:

I'll give it some more thought.

**Comment by pulver** [comment]
> How concerned are you by the fact that `make_fvar_tuple<double, N1, N2, N3>` mandates that all variables are of the same type?

Not too concened. It's a convenience method that does not prevent developers from declaring variables the regular way if they want that extra control. Most cases I think will have uniform type.

Feel free to comment/review here PR #38 Add make_ftuple().
