### ISSUE TITLE
asin(make_fvar<double, 1>(1.0));

### ISSUE THREAD

**Issue by shaneasd** [pulver/autodiff#26]
This expression fails to compile for me in VS2017. The error I get is

> C4789	buffer 'derivatives' of size 8 bytes will be overrun; 8 bytes will be written starting at offset 8

this occurs at the access of derivatives[1] inside the sqrt called by asin. This is because asin creates variable d1 with one less order than the fvar (i.e. with order 0) then calls sqrt which creates an array of derivatives of size 1 (i.e. order + 1).

It's worth noting at this point that visual studio by default does not specify /std:c++17 which means BOOST_NO_CXX17_IF_CONSTEXPR is true which means BOOST_AUTODIFF_IF_CONSTEXPR does nothing which means the else block still gets compiled. Manipulating this setting didn't make the constexpr work for me though I feel like it should so maybe there's an issue on my end there. Still in c++11 this error is expected. I can see two solutions to this:
- go back to c++11 style template programming instead of constexpr if
- change the 1 index to something like std::min(order, 1) remembering this code will never actually run for the non-1 case.

As a side note C4789 is supposed to be a warning but I described it as an error. By default, Security Developent Lifecycle checks are enabled in visual studio projects. This promotes certain security related warnings to errors including this one. Switching SDL off reverts this back to warning status.

**Comment by pulver** [comment]
Thanks. I believe I see the problem.

Not that this is the solution, but I am just wondering:
The following code is in [boost/config/compiler/visualc.hpp](https://github.com/boostorg/config/blob/develop/include/boost/config/compiler/visualc.hpp#L200)
```
// C++17 features supported by VC++ 14.1 (Visual Studio 2017) Update 3
//
#if (_MSC_VER < 1911) || (_MSVC_LANG < 201703)
#  define BOOST_NO_CXX17_STRUCTURED_BINDINGS
#  define BOOST_NO_CXX17_IF_CONSTEXPR
#  define BOOST_NO_CXX17_HDR_OPTIONAL
#  define BOOST_NO_CXX17_HDR_STRING_VIEW
#endif
```
Without using `/std:c++17` what are `_MSC_VER` and `_MSVC_LANG` and what is the actual version of your compiler?

**Comment by shaneasd** [comment]
Without specifying /std at all,
The issue is _MSVC_LANG = 201402
_MSC_VER is 1916.

**Comment by kedarbhat** [comment]
Clang just started giving me a warning about this (locally), though I'm not sure why it does suddenly (no changes to my compilation method that should suddenly trigger this).

**Comment by shaneasd** [comment]
It will depend on your usage (it's not clear whether this has changed for you). For the warning to trigger you need to be nesting more operations (that reduce the order) than the order of your variable (maybe plus or minus one). So if you're started nesting operations more deeply or using fewer independent variables this might be the cause.

**Comment by shaneasd** [comment]
It looks like lambert_w0 has the same problem except rather than a warning it generates error C2078 "too many initializers" in the creation of ```coef```

**Comment by pulver** [comment]
Pre-C++17 warnings I can live with, and would prefer over downgrading the code from C++17 in order to satisfy some compilers. I think the reported "error" in `sqrt` has been fixed.

If there are any:
* Compiler errors
* Compiler warnings with c++17 compiler flag on

then please let me know and I'll try to addresss, otherwise I'll close this issue.

**Comment by shaneasd** [comment]
Now that you mention it all of the unit tests are failing to compile for me because of an assertion in boost::mpl::aux::for_each which is used to iterate over the various numeric types under test. The failure complains that the input sequence ```all_float_types``` is not actually a sequence at all. I believe the reason for this is that mpl::begin does not have a specialization for mp11::mp_list (but I'm not certain this is true). Changing the type of ```bin_float_types``` from mp11::mp_list to boost::mpl::list seems to fix the problem.

I'm not sure what the relationship between these two libraries is or why they're both in use here. I'm also not sure what changed to cause this to start failing because it's a while since I tried to compile the tests. I also am yet to determine what compilation flag I'm using that the build system isn't that results in it not compiling for me but seemingly compiling fine here.

**Comment by shaneasd** [comment]
Actually how do I find out what command line appveyor is using to compile the code? I can't see it in the log but I'm sure I've seen it in the past.

**Comment by pulver** [comment]
Thank you for checking. It seems that appveyor is using Boost's `b2` command to compile:

1. Download and run https://github.com/boostorg/boost-ci/blob/master/ci/appveyor/install.bat Notably `%SELF%`==`autodiff` in this case.
2. For [this run](https://ci.appveyor.com/project/pulver/autodiff/branch/master/job/46xwxia7lcuofi0w) for instance the compilation command is:
`b2 libs/autodiff toolset=msvc-14.1 cxxstd=11,14,17,2a   threading=single,multi address-model=64,32 link=shared threading=single,multi variant=release -j3`

**Comment by shaneasd** [comment]
Finally managed to figure it out. It turns out the version of boost I was using 1_69_0 was different to the one used by the build system (presumably the latest) in a way that caused this compiler error. Pointing my build at the boost-root folder created by the build system fixed the issue so no compiler issues (including warnings) on my end anymore that I'm aware of.
